export type ToolCategory =
  | "Encoding"
  | "JSON"
  | "Security"
  | "Text"
  | "Time"
  | "Utilities";

export interface ToolMeta {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  iconName: string;
  route: string;
  keywords: string[];
  isPopular?: boolean;
}

export const CATEGORIES: ToolCategory[] = [
  "Encoding",
  "JSON",
  "Security",
  "Text",
  "Time",
  "Utilities",
];

export const TOOLS: ToolMeta[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON with line & column error reports",
    category: "JSON",
    iconName: "FileJson",
    route: "/dev/json",
    keywords: ["json", "format", "minify", "validate", "prettier", "parse"],
    isPopular: true,
  },
  {
    id: "json-to-typescript",
    name: "JSON → TypeScript",
    description: "Convert raw JSON payload into strongly typed TypeScript interfaces",
    category: "JSON",
    iconName: "Code2",
    route: "/dev/json-to-typescript",
    keywords: ["json", "typescript", "ts", "interface", "type", "generate", "convert"],
    isPopular: true,
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON structures side-by-side with structural diff detection",
    category: "JSON",
    iconName: "Split",
    route: "/dev/json-diff",
    keywords: ["json", "diff", "compare", "side-by-side", "changes"],
    isPopular: false,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens locally to inspect Header, Payload, and Expiration",
    category: "Security",
    iconName: "KeyRound",
    route: "/dev/jwt",
    keywords: ["jwt", "token", "decode", "bearer", "auth", "claims", "header", "payload"],
    isPopular: true,
  },
  {
    id: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode and decode standard and URL-safe Base64 strings and files",
    category: "Encoding",
    iconName: "Binary",
    route: "/dev/base64",
    keywords: ["base64", "encode", "decode", "url-safe", "unicode", "atob", "btoa"],
    isPopular: true,
  },
  {
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode/decode URI components & extract query string parameters",
    category: "Encoding",
    iconName: "Link2",
    route: "/dev/url",
    keywords: ["url", "uri", "encode", "decode", "percent", "query", "params"],
    isPopular: false,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes using Web Crypto API",
    category: "Security",
    iconName: "ShieldCheck",
    route: "/dev/hash",
    keywords: ["hash", "sha256", "sha512", "sha1", "crypto", "checksum", "digest"],
    isPopular: true,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate cryptographically secure UUID v4 tokens individually or in batch",
    category: "Utilities",
    iconName: "Fingerprint",
    route: "/dev/uuid",
    keywords: ["uuid", "guid", "v4", "random", "identifier", "generate"],
    isPopular: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions live with match highlights, capture groups, and explanation",
    category: "Text",
    iconName: "Regex",
    route: "/dev/regex",
    keywords: ["regex", "regexp", "regular expression", "test", "match", "replace", "capture"],
    isPopular: true,
  },
  {
    id: "timestamp-converter",
    name: "Unix Timestamp Converter",
    description: "Convert Unix seconds/ms timestamps to UTC, Local Date, ISO 8601 & relative times",
    category: "Time",
    iconName: "Clock",
    route: "/dev/timestamp",
    keywords: ["unix", "epoch", "timestamp", "date", "time", "iso8601", "utc"],
    isPopular: true,
  },
  {
    id: "http-header-analyzer",
    name: "HTTP Header Analyzer",
    description: "Audit HTTP response headers for security best practices (CSP, HSTS, CORS, Cookies)",
    category: "Security",
    iconName: "ShieldAlert",
    route: "/dev/headers",
    keywords: ["http", "header", "security", "csp", "hsts", "cors", "cookie", "analyzer"],
    isPopular: false,
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare plain text or code snippets line-by-line or character-by-character",
    category: "Text",
    iconName: "FileDiff",
    route: "/dev/text-diff",
    keywords: ["diff", "compare", "text", "git", "additions", "deletions"],
    isPopular: false,
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text into camelCase, snake_case, kebab-case, PascalCase, CONSTANT_CASE, etc.",
    category: "Text",
    iconName: "Type",
    route: "/dev/case-converter",
    keywords: ["case", "camelcase", "snakecase", "kebabcase", "pascalcase", "uppercase", "lowercase"],
    isPopular: false,
  },
  {
    id: "cron-helper",
    name: "Cron Expression Helper",
    description: "Parse cron schedule expressions into human-readable text & predicted execution dates",
    category: "Time",
    iconName: "CalendarClock",
    route: "/dev/cron",
    keywords: ["cron", "schedule", "crontab", "timer", "expression", "next run"],
    isPopular: false,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert HEX, RGB, HSL, RGBA color codes with live contrast accessibility test",
    category: "Utilities",
    iconName: "Palette",
    route: "/dev/color",
    keywords: ["color", "hex", "rgb", "hsl", "rgba", "wcag", "contrast", "picker"],
    isPopular: false,
  },
  {
    id: "base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between Binary, Octal, Decimal, and Hexadecimal with bit grid view",
    category: "Utilities",
    iconName: "Binary",
    route: "/dev/base-converter",
    keywords: ["binary", "octal", "hexadecimal", "decimal", "base", "bit", "converter"],
    isPopular: false,
  },
  {
    id: "random-data",
    name: "Random Data Generator",
    description: "Generate mock data records (users, addresses, UUIDs, IPs) in JSON, CSV, or SQL",
    category: "Utilities",
    iconName: "Database",
    route: "/dev/random-data",
    keywords: ["mock", "data", "faker", "random", "json", "csv", "sql", "generator"],
    isPopular: false,
  },
  {
    id: "markdown",
    name: "Markdown Previewer",
    description: "Live Markdown editor and formatted HTML converter with split-screen preview",
    category: "Text",
    iconName: "FileText",
    route: "/dev/markdown",
    keywords: ["markdown", "html", "preview", "md", "editor", "converter"],
    isPopular: false,
  },
  {
    id: "html-entities",
    name: "HTML Entity Converter",
    description: "Encode raw HTML characters into HTML entities or decode entity strings back",
    category: "Encoding",
    iconName: "Code",
    route: "/dev/html-entities",
    keywords: ["html", "entity", "escape", "unescape", "entities", "encode"],
    isPopular: false,
  },
  {
    id: "whitespace",
    name: "Whitespace Cleaner",
    description: "Strip trailing spaces, remove duplicate empty lines, convert tabs to spaces",
    category: "Text",
    iconName: "Sparkles",
    route: "/dev/whitespace",
    keywords: ["whitespace", "trim", "clean", "spaces", "tabs", "lines"],
    isPopular: false,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate cryptographically secure random passwords with custom character sets",
    category: "Security",
    iconName: "Key",
    route: "/dev/password-generator",
    keywords: ["password", "passphrase", "random", "secure", "generate", "crypto"],
    isPopular: true,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate lorem ipsum placeholder text in words, sentences, or paragraphs",
    category: "Text",
    iconName: "TextQuote",
    route: "/dev/lorem-ipsum",
    keywords: ["lorem", "ipsum", "placeholder", "dummy", "text", "sample", "paragraph"],
    isPopular: false,
  },
  {
    id: "text-stats",
    name: "Text Statistics",
    description: "Analyze text: word count, characters, sentences, reading time, keyword frequency",
    category: "Text",
    iconName: "BarChart3",
    route: "/dev/text-stats",
    keywords: ["stats", "word count", "characters", "sentences", "frequency", "reading time", "analyzer"],
    isPopular: false,
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate IPv4 network, broadcast, usable hosts, and wildcard from a CIDR block",
    category: "Utilities",
    iconName: "Network",
    route: "/dev/subnet-calculator",
    keywords: ["subnet", "cidr", "ipv4", "network", "netmask", "broadcast", "hosts", "calculator"],
    isPopular: false,
  },
  {
    id: "csv-json",
    name: "CSV ↔ JSON Converter",
    description: "Convert CSV to JSON and back with custom delimiters, quoted fields, and header rows",
    category: "Encoding",
    iconName: "FileSpreadsheet",
    route: "/dev/csv-json",
    keywords: ["csv", "json", "convert", "table", "spreadsheet", "delimiter", "parser"],
    isPopular: false,
  },
  {
    id: "http-status",
    name: "HTTP Status Codes Reference",
    description: "Browse every standard HTTP status code by class with descriptions",
    category: "Utilities",
    iconName: "Server",
    route: "/dev/http-status",
    keywords: ["http", "status", "code", "404", "500", "error", "reference", "api"],
    isPopular: false,
  },
];

export function getToolByRouteOrId(idOrRoute: string): ToolMeta | undefined {
  const clean = idOrRoute.replace(/^\/(dev|tools)\//, "");
  return TOOLS.find(
    (t) => t.id === clean || t.route === `/dev/${clean}` || t.route === `/tools/${clean}`
  );
}
